<a href="https://colab.research.google.com/github/kyawzinthant-it/sharing-github/blob/master/DhamaEducation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MOHS မှ နေ့စဉ်သတင်းထုတ်ပြန်ချက်များကို Report များအားတိုက်ရိုက် ကြည့်ရှုနိုင်ပါပြီ

In [0]:
df.style.background_gradient(cmap='Reds')

In [0]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
#style.use('ggplot')
%matplotlib inline

import plotly
import plotly.express as px
import plotly.graph_objects as go

import cufflinks as cf
import plotly.offline as pyo
from plotly.offline import init_notebook_mode,plot,iplot

import folium

In [0]:
pyo.init_notebook_mode(connected=True)
cf.go_offline()

In [0]:
df=pd.read_csv("https://raw.githubusercontent.com/kyawzinthant-it/sharing-github/master/Covid-cases-in-myanmar.csv")

In [0]:
df

    S. No. Name of State  COVID-19 confirmed cases  Recovered  Deaths  Update
0        1        Yangon                        27          0       2     1.0
1        2          Bago                         4          0       1     NaN
2        3          Chin                         3          0       0     1.0
3        4      Mandalay                         1          1       0     NaN
4        5     Naypyidaw                         1          1       0     NaN
5        6          Shan                         2          0       0     1.0
6        7           Mon                         1          0       0     NaN
7        8        Magway                         0          0       0     NaN
8        9         Kayar                         0          0       0     NaN
9       10         Kayin                         0          0       0     NaN
10      11       Sagaing                         0          0       0     NaN
11      12   Ayeyarwaddy                         0          0       0     NaN
12      13       Rakhine                         0          0       0     NaN
13      14        Kachin                         0          0       0     NaN
14      15  Thanintharyi                         0          0       0     NaN

In [0]:
df.drop(['S. No.'],axis=1,inplace=True)
df.drop(['Update'],axis=1,inplace=True)

In [0]:
df

   Name of State  COVID-19 confirmed cases  Recovered  Deaths
0         Yangon                        27          0       2
1           Bago                         4          0       1
2           Chin                         3          0       0
3       Mandalay                         1          1       0
4      Naypyidaw                         1          1       0
5           Shan                         2          0       0
6            Mon                         1          0       0
7         Magway                         0          0       0
8          Kayar                         0          0       0
9          Kayin                         0          0       0
10       Sagaing                         0          0       0
11   Ayeyarwaddy                         0          0       0
12       Rakhine                         0          0       0
13        Kachin                         0          0       0
14  Thanintharyi                         0          0       0

In [0]:
total_cases_overall=df['COVID-19 confirmed cases'].sum()
print('The total number cases till now in Myanmar is', total_cases_overall)

The total number cases till now in Myanmar is 39

In [0]:
total_cases_overall=df['Recovered'].sum()
print('The total number Recovered cases till now in Myanmar is', total_cases_overall)

The total number Recovered cases till now in Myanmar is 2

In [0]:
total_cases_overall=df['Deaths'].sum()
print('The total number Deaths cases till now in Myanmar is', total_cases_overall)

The total number Deaths cases till now in Myanmar is 3

In [0]:
Total_deaths_recovered = df['Recovered']+df['Deaths']
df['Active Cases']=df['COVID-19 confirmed cases']-Total_deaths_recovered

In [0]:
df

   Name of State  COVID-19 confirmed cases  Recovered  Deaths  Active Cases
0         Yangon                        27          0       2            25
1           Bago                         4          0       1             3
2           Chin                         3          0       0             3
3       Mandalay                         1          1       0             0
4      Naypyidaw                         1          1       0             0
5           Shan                         2          0       0             2
6            Mon                         1          0       0             1
7         Magway                         0          0       0             0
8          Kayar                         0          0       0             0
9          Kayin                         0          0       0             0
10       Sagaing                         0          0       0             0
11   Ayeyarwaddy                         0          0       0             0
12       Rakhine                         0          0       0             0
13        Kachin                         0          0       0             0
14  Thanintharyi                         0          0       0             0